### PR TITLE
Fake5 Runner task

### PR DESCRIPTION
**Pull request by matthid**
Basically a full-featured fake 5 runner task. Even added support for secret & encrypted variables to [fake](https://github.com/fsharp/FAKE/commit/929ec55bcb05b0d9ece0066c4d2c4f0ad2bce783). However secret variables are only usable when a new `Fake.BuildServer.TeamFoundation` package is released (probably soon)

Similar to other tasks it will ask the user for a version and download and cache fake. The task currently requires `DotNetCore` to be available (the easiest way is to use the `DotNetCoreInstaller` task). We can consider lifting that requirement and download the self-contained package instead (but that was out of scope for the first implementation)

I guess docs are still missing

### CODE REVIEW

**Comment by matthid** [comment]
To dogfood this in FAKE I need to add another task in order to only generate the secret variable stuff, this task is probably not very useful to anyone else but FAKE, not sure if we should add it here (it might be useful if you are not using the runner task and still want to access the secret variables)?

**Comment by matthid** [comment]
I'm quite positive that this is ready, I hope I didn't break the PaketRestore task

**Comment by matthid** [comment]
Maybe for marketing purposes we should have a separate "fake" extension (to be independent of "F#")? However I'm fine with having everything here in a single repository. What do you think?

**Comment by isaacabraham** [comment]
@matthid I had the same thought re: FAKE - I'm happy to support either model :-)

**Comment by isaacabraham** [comment]
And thanks for adding this :-)

**Comment by matthid** [comment]
Thinking this further: "Paket" is not a "F# helper" either... Maybe we should rename this completely :/

**Comment by isaacabraham** [comment]
Yeah, it is a bit misleading. Not sure what to rename it to, as it has an F# runner there too.

**Comment by matthid** [comment]
The good thing about a single extension is that people need to ask their admins only once, while with 3 extensions (Paket, Fake, F#) they might need to ask multiple times :/

**Comment by matthid** [comment]
And realistically that the tasks are used and installed together makes completely sense to me

**Pull request merged**
